### ISSUE TITLE
getExtension breaks with no output

### ISSUE THREAD

**Issue by DavidGOrtega** [node-3d/webgl-raub#2]
```js
const webgl = require('node-webgl-raub');
webgl.getExtension && webgl.getExtension('WEBGL_color_buffer_float');

const canvas = document.createElement('canvas'); // === doc
const gl = canvas.getContext('webgl'); 
console.log( gl.getExtension('WEBGL_color_buffer_float') );
```

**Comment by raub** [comment]
Hello, sorry for the long absence, I've had a vacation. So did you get this solved? I see you use some deeply old stuff, that might be the reason to this error. Be sure to use https://www.npmjs.com/package/webgl-raub and not `node-webgl-raub`, but `webgl-raub` (the former is obsolete).

**Comment by raub** [comment]
Ok, I've got a **workaround**: use `GL_ARB_color_buffer_float`.
The [example](https://github.com/node-3d/webgl-raub/blob/master/examples/extensions.js) has helped me finding this out.

Now the issue is that `webgl-raub` has no WebGL extensions, it has OpenGL ones. I'll have to provide a fallback to convert them seamlessly.

**Comment by DavidGOrtega** [comment]
Hi! Thanks for the reply.

Yeah I did that trick, I got the supported extensions and then I mapped the extensions that I need. But you are right, the project needs the WebGL extensions.

WEBGL_color_buffer_float
OES_texture_float
to GL_ARB_texture_float

EXT_color_buffer_float
to GL_ARB_color_buffer_float

Still missing some:
EXT_disjoint_timer_query
WEBGL_lose_context

**Comment by raub** [comment]
I've checked the CPP code and found that it does nothing, i.e. **no-op**. If the extension exists it simply returns its name, otherwise null.

As I have actually forked this repo from **node-webgl**, I went there to see if they have adressed this issue. And no, they also [didn't](https://github.com/mikeseven/node-webgl/blob/master/src/webgl.cc#L1759).

According to the current state (of **webgl-raub**) it might be implemented as `gl.getExtension = (x => x);`. But [the spec](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/getExtension) describes it in a different way. And also there are native GL extensions available with no meaningful way to use them form JS in a generic way...

So it's not enough to just map some extension names. There is a lot missing, and I'm going to implement the stuff, but I also accept PRs if any.

**Comment by raub** [comment]
@DavidGOrtega could you please clarify on your usecase with extensions? Is it for compatibility reasons or you really need to use exotic extensions like those `EXT_disjoint_timer_query` and `WEBGL_lose_context`?

For the time being I'm going to provide mocks like here: https://github.com/node-3d/webgl-raub/commit/9af6d57ecc2f847018a6305ac59e6901bb741948#diff-c166a87becc5345103d00149dc71c2c1

**Comment by raub** [comment]
Mocks for extensions are provided in v2.0.0
`npm i webgl-raub@2.0.0`

Also available since https://github.com/node-3d/3d-core-raub/tree/v1.0.0
`npm i 3d-core-raub@1.0.0`

**Comment by DavidGOrtega** [comment]
@raub sorry for the late response, I didn't notice the messages. My intention is to give access to opengl for tfjs. So basically has to be a partially supported WebGL 2 specification.

**Comment by raub** [comment]
@DavidGOrtega could you please create a new issue regarding that feature request and be more specific on what is lacking? Maybe even provide a link if your code is open, so that I could test my modules against it.
