### ISSUE TITLE
Missing props for WebGL needed for ThreeJS

### ISSUE THREAD

**Issue by bvkimball** [node-3d/webgl-raub#21]
Ok,

I am trying to write a React wrapper for `glfw-raub` and `webgl-raub`... so i can then use them in react-three-fiber.
I am using `3d-core-raub` as a reference implementation

I am using threejs v0.128.x

Got an error that `gl.canvas` was undefined here.
https://github.com/mrdoob/three.js/blob/da14c33181a90419820c04b5201d66b1401c1581/src/renderers/webgl/WebGLState.js#L1117

^^^ WebGLRenderingContext is supposed to have a reference to the canvas that created it, i guess.  i set this manually and got past this error.

ThreeJS expects a WebGLRenderingContext, but you use your WebGL class in all your examples.  Its fine if it is the same object but for typescript maybe they could be masked behind getters that return that right context.

in your examples you set `viewportWidth` & Height, but those properties don't exist... 
also tried to use `drawingBufferWidth` & height and they were null.

Just notes to help anyone else with this issue.

**Comment by raub** [comment]
In `webgl-raub@2.3.0`, I've changed how `drawingBufferWidth` works. Now it uses `gl.canvas.width` if `gl.canvas` is available. It is still necessary to assign `gl.canvas` manually, because this should be done in `glfw-raub` - as a separate update. The automatic assignment will be added in a future version of `glfw-raub`. Also updated the examples here.
