### ISSUE TITLE
How can i output an canvas image?

### ISSUE THREAD

**Issue by axmand** [node-3d/webgl-raub#4]
Hi~
It is really a good job. In my use, I am puzzled... where can I see the results after using webgl drawn a graph？

**Comment by raub** [comment]
Hello! Do you use this module with the "3d-core-raub" package? If so, you should have a desktop window where everything is drawn. If you want to store the picture from that window, it basically means "to make snapshot". Since we work with GL you probably can use [glReadPixels](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glReadPixels.xml). When done, the picture is in the provided buffer (in memory) and you are to store it as you wish.

As a good use-case I'd like to provide a working example of such application. I'll inform you if I succeed.

**Comment by raub** [comment]
@axmand please look at [this example](https://github.com/node-3d/3d-core-raub/blob/master/examples/snapshot.js#L32), maybe even run it...

It's a bit dirty, because I had to mimic the BMP file format for FreeImage, but hey it works anyway. And you can save whatever format Freeimage saves (bmp, gif, jpg, tga, webp - to name just few).

Is that what you wanted to achieve? Does it solve your problem?

**Comment by axmand** [comment]
> Hello! Do you use this module with the "3d-core-raub" package? If so, you should have a desktop window where everything is drawn. If you want to store the picture from that window, it basically means "to make snapshot". Since we work with GL you probably can use [glReadPixels](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glReadPixels.xml). When done, the picture is in the provided buffer (in memory) and you are to store it as you wish.
> 
> As a good use-case I'd like to provide a working example of such application. I'll inform you if I succeed.


I am very grateful for your tips.
I followed your prompt and it has run smoothly  by using "3d-core-raub" instead, The code that can be run is as follows:
``` javascript
const node3d = require("3d-core-raub");
global.document = global.window = node3d.doc;
const requestAnimationFrame = window.requestAnimationFrame;
const {gl,Screen} = node3d;
const screen = new Screen();
//your own gl rendering
const updateFrame = ()=>{
   //something else
   requestAnimationFrame(updateFrame);
   screen.draw();
};
updateFrame();
```

**Comment by raub** [comment]
Oh, I see. Anyway, I'm glad it has worked for you. Consider looking at all the [examples](https://github.com/node-3d/3d-core-raub/tree/master/examples), you can find some nice snippets there.
