### ISSUE TITLE
How to enable argument coercion like the browser's WebGL APIs?

### ISSUE THREAD

**Issue by trusktr** [node-3d/webgl-raub#9]
https://github.com/node-3d/webgl-raub/blob/6cef8ce8b65859845e50713e4debe63092c2ceb6/src/cpp/attrib.cpp#L238-L252

I was trying to pass numbers for argument 3 `normalized` (f.e. `0` or `1`) instead of booleans, and this causes the error:

```
vertexAttrib4fv error
Error: Argument 3 must be of type `Bool` or be `null`/`undefined`
```

So on the JS side I had to cast my values (which I don't have to do in a browser) like so:

```
gl.vertexAttribPointer(..., !!normalized, ...)
```

The browser automatically coerces values, so no need ton manually convert them.

Is there some way to fix this?

**Comment by raub** [comment]
Hello. Well, yeah, it's rather strict on the C++ side. There are several possible solutions. The simplest one yet, is to use this https://github.com/node-3d/webgl-raub/blob/master/js/webgl.js#L47 function in a wrapper. As you might see from `webgl.js`, there is no wrapper for `gl.vertexAttribPointer`, that's why no pre-processing happens for this method specifically. It should be:

```
const _vertexAttribPointer = gl.vertexAttribPointer;
gl.vertexAttribPointer = (indx, size, type, normalized, stride, vertices) => _vertexAttribPointer(
	indx, size, type, enforceBool(normalized), stride, vertices
);
```

Maybe there are more methods, that miss wrappers. I think, a better solution would be to add more coercion on C++ side, in `*_BOOL_ARG` and other macros.

**Comment by raub** [comment]
In glfw-raub@4.6.0 I tried to add the boolean coercion to all the boolean-receiving methods, including `gl.vertexAttribPointer`. It should have fixed the issue.
